image: eu.gcr.io/x5-omega-messenger-8/services:v12

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: ./gradlew assemble
  artifacts:
    expire_in: 4 days
    paths:
      - .gradle/
      - build/

unittests:
  stage: test
  script: ./gradlew test
  artifacts:
    name: "reports_unittests_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when: on_failure
    expire_in: 4 days
    paths:
      - build/reports/tests/

#androidtests:
#  stage: test
#  script:
#    - /opt/android-sdk/emulator/emulator -avd x86 -no-audio -no-window &
#    - /opt/android-sdk/platform-tools/adb wait-for-device
#    - sleep 5
#    - ./gradlew connectedAndroidTest
#  artifacts:
#    name: "reports_androidtests_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
#    when: on_failure
#    expire_in: 4 days
#    paths:
#      - build/reports/androidTests/

deploy:
  stage: deploy
  script: ./gradlew publish
  dependencies:
    - build
  only:
    - tags
