image: eu.gcr.io/x5-omega-messenger-8/services:v12

stages:
  - build
  - test
  - deploy

Build:
  stage: build
  script: ./gradlew assemble -x lint --parallel --quiet
  artifacts:
    name: "${CI_PROJECT_NAME}.build.${CI_COMMIT_SHORT_SHA}"
    paths:
      - .gradle/
      - build/

Unit Tests:
  stage: test
  script:
    - ./gradlew test jacocoTestReport -x lint --parallel --quiet
    - grep -oP "(Total)(.*?)(\d{1,3}%)" "build/reports/jacoco/jacocoTestReport/html/index.html"
  artifacts:
    name: "${CI_PROJECT_NAME}.unittests.${CI_COMMIT_SHORT_SHA}"
    paths:
      - build/reports/

Lint:
  stage: test
  script: ./gradlew lint --parallel --quiet
  artifacts:
    name: "${CI_PROJECT_NAME}.lint.${CI_COMMIT_SHORT_SHA}"
    when: on_failure
    paths:
      - build/reports/

Android Tests:
  stage: test
  tags:
    - board # Requires a board
  script:
    - ./gradlew connectedAndroidTest
  artifacts:
    name: "${CI_PROJECT_NAME}.androidtests.${CI_COMMIT_SHORT_SHA}"
    when: on_failure
    paths:
      - build/reports/

Deploy on Maven:
  stage: deploy
  script: ./gradlew publish
  dependencies:
    - Build
  only:
    - tags
